### PR TITLE
layers:Fix race in decompression shader

### PR DESCRIPTION
**Pull request by vkushwaha-nv**

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
That failure was in a test for the sync2 layer. Retriggering

**Comment by jeremyg-lunarg** [comment]
I have another job running with your tests reenabled which won't show up here.

**Comment by jeremyg-lunarg** [comment]
Galaxy S23 is still failing:
```
[----------] 2 tests from DecompressionTest
[ RUN      ] DecompressionTest.DecompressMemory
/home/lunarg/.jenkins/wvel/Debug64/Vulkan-ExtensionLayer/tests/vktestbinding.cpp:295: Failure
Failed
Assertion: `vk::CreateDevice(phy_.handle(), &info, __null, &dev) == VK_SUCCESS'

```

**Comment by vkushwaha-nv** [comment]
And pixel 7?
Would it be possible for you to collect the error code that vk::CreateDevice is failing with on Galaxy S23 ?

**Comment by jeremyg-lunarg** [comment]
> And pixel 7? Would it be possible for you to collect the error code that vk::CreateDevice is failing with on Galaxy S23 ?

Pixel 7 passed on this run.

**Comment by jeremyg-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/329 should cause error codes to be reported, but you'll need to rebase once I get it merged.

**Comment by vkushwaha-nv** [comment]
Ok, I think we should merge this change upstream.

**Comment by jeremyg-lunarg** [comment]
> Ok, I think we should merge this change upstream.

it is merged now, please rebase

**Comment by vkushwaha-nv** [comment]
> #329 should cause error codes to be reported, but you'll need to rebase once I get it merged.

Trying here https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/330

**Pull request merged**
