### PR TITLE
layers: Check logging on createdevice

### PR DESCRIPTION
**Pull request by vkushwaha-nv**

### CODE REVIEW

**Comment by vkushwaha-nv** [comment]
Do not commit. This is to get logging info on Galaxy device.

**Comment by jeremyg-lunarg** [comment]
I'll run this with your test reenabled now

**Comment by jeremyg-lunarg** [comment]
Pixel7 was pass that time, Galaxy S23:
```
[----------] 2 tests from DecompressionTest
[ RUN      ] DecompressionTest.DecompressMemory
Memory decompression feature not available in the driver, enabling decompression layer.
creating device with layer support   
   Info: subgroupSize 64
Info: bytecodeIndex 7
Info: Memory Heaps/Types:
    Heap 0: Size 7424892928, Flags 1
    Heap 1: Size 268435456, Flags 1
    Memory Type 0: HeapIndex 0, Flags 1
    Memory Type 1: HeapIndex 0, Flags 1
    Memory Type 2: HeapIndex 0, Flags 1
    Memory Type 3: HeapIndex 0, Flags 11
    Memory Type 4: HeapIndex 0, Flags 7
    Memory Type 5: HeapIndex 0, Flags 7
    Memory Type 6: HeapIndex 0, Flags 15
    Memory Type 7: HeapIndex 1, Flags 33
    Memory Type 8: HeapIndex 0, Flags 17
Info: Using memory index 4 for indirectDispatch Buffer.
Error: CreatePipelineState failed with error 4294967283
/home/lunarg/.jenkins/wvel/Debug64/Vulkan-ExtensionLayer/tests/vktestbinding.cpp:281: Failure
Expected equality of these values:
  (result = vk::CreateDevice(phy_.handle(), &info, __null, &dev))
    Which is: -13
  VK_SUCCESS
    Which is: 0

/home/lunarg/.jenkins/wvel/Debug64/Vulkan-ExtensionLayer/tests/vkrenderframework.cpp:942: Failure
Expected: (true) != (graphics_queues().empty()), actual: true vs true
```

**Comment by jeremyg-lunarg** [comment]
here's a pixel 7 log:
```
[----------] 2 tests from DecompressionTest
[ RUN      ] DecompressionTest.DecompressMemory
Memory decompression feature not available in the driver, enabling decompression layer.
creating device with layer support   
   Info: subgroupSize 16
Info: bytecodeIndex 5
Info: Memory Heaps/Types:
    Heap 0: Size 7786545152, Flags 1
    Heap 1: Size 104857600, Flags 1
    Memory Type 0: HeapIndex 0, Flags 7
    Memory Type 1: HeapIndex 0, Flags 11
    Memory Type 2: HeapIndex 0, Flags 17
    Memory Type 3: HeapIndex 1, Flags 33
Info: Using memory index 0 for indirectDispatch Buffer.
Info: vkCmdDecompressMemoryNV: Using VK_LAYER_KHRONOS_memory_decompression layer
Info: vkCmdDecompressMemoryNV: Using VK_LAYER_KHRONOS_memory_decompression layer
/home/lunarg/.jenkins/wvel/Debug64/Vulkan-ExtensionLayer/tests/decompression_tests.cpp:120: Failure
Value of: compareResult == 0
  Actual: false
Expected: true

[  FAILED  ] DecompressionTest.DecompressMemory (602 ms)
[ RUN      ] DecompressionTest.DecompressMemoryIndirect
Memory decompression feature not available in the driver, enabling decompression layer.
creating device with layer support   
   Info: subgroupSize 16
Info: bytecodeIndex 5
Info: Memory Heaps/Types:
    Heap 0: Size 7786545152, Flags 1
    Heap 1: Size 104857600, Flags 1
    Memory Type 0: HeapIndex 0, Flags 7
    Memory Type 1: HeapIndex 0, Flags 11
    Memory Type 2: HeapIndex 0, Flags 17
    Memory Type 3: HeapIndex 1, Flags 33
Info: Using memory index 0 for indirectDispatch Buffer.
Info: vkCmdDecompressMemoryIndirectCountNV: Using VK_LAYER_KHRONOS_memory_decompression layer
/home/lunarg/.jenkins/wvel/Debug64/Vulkan-ExtensionLayer/tests/decompression_tests.cpp:220: Failure
Value of: compareResult == 0
  Actual: false
Expected: true

```

**Comment by vkushwaha-nv** [comment]
Ok, I think it would be nice to get help from Google on why that shader miscompares on Pixel 7.

And get help from Samsung on why CreatePipelineState() is failing with error VK_UNKNOWN.

**Pull request closed without merging**
