### PR TITLE
layers: Fix race issue in decompression layer

### PR DESCRIPTION
**Pull request by vkushwaha-nv**
May fix issue 312

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
The internal CI run that passed over the weekend has the decompression tests disabled on the failing devices. I'll start another run with those tests reenabled.

**Comment by jeremyg-lunarg** [comment]
> Device::init_queues() may be unrelated to my change, because this change only modified the shader. Can you check if that problem existed before?

Most likely there's a bug in your test and yeah it probably existed before. Probably the test is requesting an extension or feature that isn't present on this device. I can send you the vulkaninfo output for it in a minute but I don't have time for remote control debugging experiments. If you find something suspicious, update the PR and I'll start another CI run.

**Comment by jeremyg-lunarg** [comment]
[vulkaninfo_Samsung_Galaxy_S32_Ultra.txt](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/files/12786898/vulkaninfo_Samsung_Galaxy_S32_Ultra.txt)

**Comment by jeremyg-lunarg** [comment]
[vulkaninfo_Google_Pixel_7.txt](https://github.com/KhronosGroup/Vulkan-ExtensionLayer/files/12786905/vulkaninfo_Google_Pixel_7.txt)

**Comment by vkushwaha-nv** [comment]
Looks like https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/328 also fails on Android?

**Comment by jeremyg-lunarg** [comment]
closing this in favor of https://github.com/KhronosGroup/Vulkan-ExtensionLayer/pull/328 .  In the future please use `git push -f your-pr-branch` to update the code in a PR rather than making a new one.

**Pull request closed without merging**
