### PR TITLE
layers: Add logging to decompression

### PR DESCRIPTION
**Pull request by vkushwaha-nv**
Just a debug PR to check logging

### CODE REVIEW

**Comment by juan-lunarg** [comment]
> CI Vulkan-ExtensionLayer build # 448 failed.

@Tony-LunarG the Jenkins job failed normally 20 hours ago. But LunarG CI Checkrun didn't detect the failure?

**Comment by Tony-LunarG** [comment]
> > CI Vulkan-ExtensionLayer build # 448 failed.
> 
> @Tony-LunarG the Jenkins job failed normally 20 hours ago. But LunarG CI Checkrun didn't detect the failure?

It detected it but reporting went wrong:
Error: Bad Gateway for url: https://api.github.com/repos/KhronosGroup/Vulkan-ExtensionLayer/check-runs/

**Comment by juan-lunarg** [comment]
Updating with rebase against main due to https://github.com/KhronosGroup/Vulkan-ExtensionLayer/commit/653145c8224061323b7e685dfb5bbf4fa87008be

**Comment by jeremyg-lunarg** [comment]
please rebase to pick up CI fixes

**Pull request closed without merging**
