### PR TITLE
build: Update Vulkan-Headers 1.3.245

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
This change also updates the code generation scripts to match the latest from Vulkan-ValidationLayers

### CODE REVIEW

**Review by juan-lunarg — DISMISSED** [review]

**Comment by jeremyg-lunarg** [comment]
Weird problems in generated code:
```
/home/lunarg/.jenkins/wvel/Release64/Vulkan-ExtensionLayer/utils/generated/vk_safe_struct.cpp: In constructor âsafe_VkAccelerationStructureTrianglesDisplacementMicromapNV::safe_VkAccelerationStructureTrianglesDisplacementMicromapNV(const VkAccelerationStructureTrianglesDisplacementMicromapNV*)â:
/home/lunarg/.jenkins/wvel/Release64/Vulkan-ExtensionLayer/utils/generated/vk_safe_struct.cpp:56190:59: warning: left operand of comma operator has no effect [-Wunused-value]
56190 |         ppUsageCounts = new VkMicromapUsageEXT[in_struct->usageCountsCount,1];
      |                                                ~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/lunarg/.jenkins/wvel/Release64/Vulkan-ExtensionLayer/utils/generated/vk_safe_struct.cpp:56190:25: error: cannot convert âVkMicromapUsageEXT*â to âconst VkMicromapUsageEXT* const*â in assignment
56190 |         ppUsageCounts = new VkMicromapUsageEXT[in_struct->usageCountsCount,1];
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         VkMicromapUsageEXT*
/home/lunarg/.jenkins/wvel/Release64/Vulkan-ExtensionLayer/utils/generated/vk_safe_struct.cpp:56191:130: error: too many arguments to function âvoid* memcpy(void*, const void*, size_t)â
56191 |         memcpy ((void *)ppUsageCounts, (void *)in_struct->ppUsageCounts, sizeof(VkMicromapUsageEXT)*in_struct->usageCountsCount,1);
      |                                                                                                                                  ^
In file included from /usr/include/features.h:461,
```

**Comment by juan-lunarg** [comment]
> Weird problems in generated code:

+ @mikes-lunarg

**Comment by mikes-lunarg** [comment]
> Weird problems in generated code:
> 

I had to manually add a safe struct workaround to VVL for this https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/2cd22aa2add2b4dcf1dc422c880bcca97220578d#diff-6cb4072fbb883af4aa2e29886c4425a795cf86487bdd9920aba0404c1a1dc0f8R1466-R1477

**Comment by jeremyg-lunarg** [comment]
> > Weird problems in generated code:
> 
> I had to manually add a safe struct workaround to VVL for this [KhronosGroup/Vulkan-ValidationLayers@2cd22aa#diff-6cb4072fbb883af4aa2e29886c4425a795cf86487bdd9920aba0404c1a1dc0f8R1466-R1477](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/2cd22aa2add2b4dcf1dc422c880bcca97220578d#diff-6cb4072fbb883af4aa2e29886c4425a795cf86487bdd9920aba0404c1a1dc0f8R1466-R1477)

I updated the scripts directory to match VVL again, seems to be working now.

**Review by juan-lunarg — APPROVED** [review]

**Pull request merged**
