### PR TITLE
build: Remove ndk-build

### PR DESCRIPTION
**Pull request by juan-lunarg**
Use CMake fully for Android

### CODE REVIEW

**Comment by juan-lunarg** [comment]
> CI Vulkan-ExtensionLayer build # 690 running.

Jenkins testing will fail until my changes to VulkanTests are merged.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM. huzzah!

**Comment by juan-lunarg** [comment]
> CI Vulkan-ExtensionLayer build # 692 passed.

CI is now using CMake for Android 💯

**Comment by juan-lunarg** [comment]
Testing passed on my fork. KhronosGroup github actions running super slow today...

**Pull request merged**
